name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PY_COLORS: 1

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
      - run: ruff check .
      - run: ruff format --check .
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18.3
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      memcached:
        image: memcached:1.6.41-alpine
        ports:
          - 11211:11211
      redis:
        image: redis:8.6.1-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
        with:
          version: '0.10.9'
          enable-cache: false
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Setup required upstream yarn version
        run: yarn set version 1.22.21
      - run: |
          sudo apt-get update && sudo apt-get install -y libxmlsec1-dev libmaxminddb-dev
          uv sync --frozen
          make deps
          uv run pytest
